name: build

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up java
      uses: actions/setup-java@v2.1.0
      with:
        distribution: 'adopt'
        java-version: 17
        java-package: jre

    - name: Build
      run: ./mill indexer.assembly

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push images
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/torrentdamdev/indexer:latest, ghcr.io/torrentdamdev/indexer:${{ github.sha }}
